# Generated by Django 5.1.3 on 2025-02-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_controlsetpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawactuatormonitor',
            name='state',
            field=models.TextField(db_column='state'),
        ),
    ]
