# Generated by Django 5.1.3 on 2025-02-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rawactuatormonitor_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawactuatormonitor',
            name='state',
            field=models.IntegerField(db_column='state'),
        ),
    ]
