# Generated by Django 5.1.3 on 2025-03-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_rawactuatormonitor_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanDevide',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('uuid', models.TextField(db_column='uuid')),
                ('device_name', models.TextField(db_column='device_name')),
                ('mac', models.TextField(db_column='mac')),
                ('address_type', models.TextField(db_column='address_type')),
                ('oob_info', models.TextField(db_column='oob_info')),
                ('adv_type', models.IntegerField(db_column='adv_type')),
                ('bearer_type', models.TextField(db_column='bearer_type')),
                ('rssi', models.IntegerField(db_column='rssi')),
            ],
        ),
    ]
