# Generated by Django 5.1.3 on 2025-03-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scandevide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScanDevide',
            new_name='ScanDevice',
        ),
    ]
