# Generated by Django 5.1.3 on 2025-03-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_scandevide_scandevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='scandevice',
            name='room_id',
            field=models.ForeignKey(db_column='room_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_id', verbose_name='Refering to id of room where this node is implemented'),
        ),
    ]
