# Generated by Django 5.1.3 on 2025-03-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_scandevice_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationnode',
            name='address_type',
            field=models.TextField(db_column='address_type', null=True),
        ),
        migrations.AddField(
            model_name='registrationnode',
            name='adv_type',
            field=models.IntegerField(db_column='adv_type', null=True),
        ),
        migrations.AddField(
            model_name='registrationnode',
            name='bearer_type',
            field=models.TextField(db_column='bearer_type', null=True),
        ),
        migrations.AddField(
            model_name='registrationnode',
            name='device_name',
            field=models.TextField(db_column='device_name', null=True),
        ),
        migrations.AddField(
            model_name='registrationnode',
            name='oob_info',
            field=models.TextField(db_column='oob_info', null=True),
        ),
        migrations.AddField(
            model_name='registrationnode',
            name='rssi',
            field=models.IntegerField(db_column='rssi', null=True),
        ),
        migrations.AlterField(
            model_name='registrationnode',
            name='function',
            field=models.TextField(db_column='function', default='None'),
        ),
        migrations.AlterField(
            model_name='registrationnode',
            name='x_axis',
            field=models.IntegerField(db_column='x_axis', default=1),
        ),
        migrations.AlterField(
            model_name='registrationnode',
            name='y_axis',
            field=models.IntegerField(db_column='y_axis', default=1),
        ),
        migrations.AlterField(
            model_name='registrationnode',
            name='z_axis',
            field=models.IntegerField(db_column='z_axis', default=1),
        ),
    ]
