# Generated by Django 5.1.3 on 2025-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_registrationnode_address_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationnode',
            name='unicast',
            field=models.IntegerField(db_column='unicast', null=True),
        ),
    ]
