# Generated by Django 5.1.3 on 2025-03-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_registrationnode_unicast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scandevice',
            name='uuid',
            field=models.TextField(db_column='uuid', unique=True),
        ),
    ]
