# Generated by Django 5.1.3 on 2025-03-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_scandevice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationnode',
            name='mac',
            field=models.TextField(db_column='mac', null=True),
        ),
        migrations.AlterField(
            model_name='scandevice',
            name='uuid',
            field=models.TextField(db_column='uuid'),
        ),
    ]
