# Generated by Django 5.1.3 on 2025-03-24 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_registrationnode_mac_alter_scandevice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationnode',
            name='uuid',
            field=models.TextField(db_column='uuid', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scandevice',
            name='room_id',
            field=models.ForeignKey(db_column='room_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_id', verbose_name='Refering to id of room where this node is implemented'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scandevice',
            name='uuid',
            field=models.TextField(db_column='uuid', unique=True),
        ),
    ]
