# Generated by Django 5.1.3 on 2025-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_registrationnode_uuid_alter_scandevice_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationnode',
            name='x_axis',
            field=models.FloatField(db_column='x_axis', default=1),
        ),
        migrations.AlterField(
            model_name='registrationnode',
            name='y_axis',
            field=models.FloatField(db_column='y_axis', default=1),
        ),
        migrations.AlterField(
            model_name='registrationnode',
            name='z_axis',
            field=models.FloatField(db_column='z_axis', default=1),
        ),
    ]
