# Generated by Django 5.1.3 on 2025-03-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_registrationnode_x_axis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationnode',
            name='address_type',
            field=models.IntegerField(db_column='address_type', null=True),
        ),
        migrations.AlterField(
            model_name='registrationnode',
            name='oob_info',
            field=models.IntegerField(db_column='oob_info', null=True),
        ),
        migrations.AlterField(
            model_name='scandevice',
            name='address_type',
            field=models.IntegerField(db_column='address_type'),
        ),
        migrations.AlterField(
            model_name='scandevice',
            name='oob_info',
            field=models.IntegerField(db_column='oob_info'),
        ),
    ]
