# Generated by Django 5.1.3 on 2025-04-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_registrationnode_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepermission',
            name='node_id',
            field=models.OneToOneField(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, to='api.registrationnode', to_field='node_id'),
        ),
    ]
