# Generated by Django 5.1.3 on 2025-04-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_employeepermission_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationnode',
            name='remote_enable',
            field=models.IntegerField(db_column='remote_enable', null=True),
        ),
        migrations.AddField(
            model_name='registrationnode',
            name='remote_unicast',
            field=models.IntegerField(db_column='remote_unicast', null=True),
        ),
    ]
