# Generated by Django 5.1.3 on 2025-04-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_registrationnode_remote_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scandevice',
            name='remote_enable',
            field=models.IntegerField(db_column='remote_enable', null=True),
        ),
        migrations.AddField(
            model_name='scandevice',
            name='remote_unicast',
            field=models.IntegerField(db_column='remote_unicast', null=True),
        ),
    ]
