# Generated by Django 5.1.3 on 2025-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_scandevice_remote_enable_scandevice_remote_unicast'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationnode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/room'),
        ),
    ]
