# Generated by Django 5.1.3 on 2025-04-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_registrationnode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationnode',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/room'),
        ),
    ]
