# Generated by Django 5.1.3 on 2025-04-24 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_registrationnode_image_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAlgorithm',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('image_decode', models.ImageField(blank=True, null=True, upload_to='images/result/decode')),
                ('image_encode', models.ImageField(blank=True, null=True, upload_to='images/result/encode')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_id', verbose_name='Refering to id of room where this node is implemented')),
            ],
        ),
    ]
