# Generated by Django 5.1.3 on 2025-04-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_resultalgorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultalgorithm',
            name='algorithm',
            field=models.TextField(blank=True, db_column='algorithm', null=True),
        ),
    ]
