# Generated by Django 5.1.3 on 2025-04-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_resultalgorithm_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultalgorithm',
            name='image_decode',
            field=models.ImageField(blank=True, db_column='image_decode', null=True, upload_to='images/result/decode'),
        ),
        migrations.AlterField(
            model_name='resultalgorithm',
            name='image_encode',
            field=models.ImageField(blank=True, db_column='image_encode', null=True, upload_to='images/result/encode'),
        ),
    ]
