# Generated by Django 5.1.3 on 2025-06-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_resultalgorithm_image_decode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlsetpoint',
            name='temp',
        ),
    ]
