# Generated by Django 5.1.3 on 2025-06-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_controlsetpoint_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlsetpoint',
            name='time',
        ),
        migrations.AlterField(
            model_name='controlsetpoint',
            name='start_time',
            field=models.BigIntegerField(db_column='start_time', null=True),
        ),
    ]
