# Generated by Django 5.1.3 on 2025-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_controlsetpoint_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsetpoint',
            name='setpoint',
            field=models.IntegerField(db_column='setpoint', null=True),
        ),
    ]
