[supervisord]
nodaemon=true

[program:django]
command=python3 manage.py runserver 0.0.0.0:8000
directory=/usr/src/app/
autostart=true
autorestart=true
stdout_logfile=/var/log/runserver.log
stderr_logfile=/var/log/runserver.err.log

[program:data_from_gateway]
command=python3 data_from_gateway.py
directory=/usr/src/app/api/
autostart=true
autorestart=true
stdout_logfile=/var/log/data_from_gateway.log
stderr_logfile=/var/log/data_from_gateway.err.log

